# Generated by Django 4.1.5 on 2023-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('per', 'personal'), ('edu', 'education'), ('spo', 'sport'), ('buy', 'to buy')], max_length=3)),
                ('priority', models.CharField(choices=[(1, 'first'), (2, 'second'), (3, 'do later')], max_length=1)),
            ],
        ),
    ]
