# Generated by Django 4.1.5 on 2023-01-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_done_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('ur', 'urgent'), ('im', 'important'), ('la', 'do later')], max_length=2),
        ),
    ]
